
DEFSYM(command)
DEFSYM(control)
DEFSYM(GetKeyHandler)
DEFSYM(key)
DEFSYM(option)
DEFSYM(platformVariables)
DEFSYM(platformFunctions)
DEFSYM(platformWeakFunctions)
DEFSYM(protoEditor)
DEFSYM(shift)
DEFSYM(__origFunctions)
DEFSYM(__origVars)
DEFSYM(__platform)
